#ifndef WAYWAL_SHADERS_EMBEDDED_H
#define WAYWAL_SHADERS_EMBEDDED_H

static const char *SHADER_SRC_FADE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, u_progress).bgra);\n"
    "}\n";

static const char *SHADER_SRC_WIPE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_angle;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 dir = vec2(cos(u_angle), sin(u_angle));\n"
    "    float proj = dot(uv - vec2(0.5), dir) / 1.41421356 + 0.5;\n"
    "    float edge = 0.04;\n"
    "    float alpha = smoothstep(proj - edge, proj + edge, u_progress);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha).bgra);\n"
    "}\n";

static const char *SHADER_SRC_GROW =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2 u_center;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    vec2 delta = uv - u_center;\n"
    "    delta.x *= aspect;\n"
    "    float dist = length(delta);\n"
    "    float max_dist = length(vec2(max(u_center.x, 1.0 - u_center.x) * aspect,\n"
    "                                 max(u_center.y, 1.0 - u_center.y)));\n"
    "    float r = u_progress * (max_dist + 0.05);\n"
    "    float edge = 0.03 * (max_dist + 0.05);\n"
    "    float alpha = smoothstep(dist - edge, dist + edge, r);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha).bgra);\n"
    "}\n";

static const char *SHADER_SRC_OUTER =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2 u_center;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    vec2 delta = uv - u_center;\n"
    "    delta.x *= aspect;\n"
    "    float dist = length(delta);\n"
    "    float max_dist = length(vec2(max(u_center.x, 1.0 - u_center.x) * aspect,\n"
    "                                 max(u_center.y, 1.0 - u_center.y)));\n"
    "    float r = (1.0 - u_progress) * (max_dist + 0.05);\n"
    "    float edge = 0.03 * (max_dist + 0.05);\n"
    "    float alpha = smoothstep(r - edge, r + edge, dist);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha).bgra);\n"
    "}\n";

static const char *SHADER_SRC_WAVE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_angle;\n"
    "uniform float u_wave_freq;\n"
    "uniform float u_wave_amp;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 dir = vec2(cos(u_angle), sin(u_angle));\n"
    "    vec2 perp = vec2(-dir.y, dir.x);\n"
    "    float proj = dot(uv - vec2(0.5), dir) / 1.41421356 + 0.5;\n"
    "    float cross_proj = dot(uv - vec2(0.5), perp);\n"
    "    float wave = sin(cross_proj * u_wave_freq) * u_wave_amp;\n"
    "    float d = proj + wave;\n"
    "    float edge = 0.04;\n"
    "    float alpha = smoothstep(d - edge, d + edge, u_progress);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha).bgra);\n"
    "}\n";

static const char *SHADER_SRC_NOISE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "float hash21(vec2 p) {\n"
    "    p = fract(p * vec2(123.34, 456.21));\n"
    "    p += dot(p, p + 45.32);\n"
    "    return fract(p.x * p.y);\n"
    "}\n"
    "float noise(vec2 uv) {\n"
    "    vec2 i = floor(uv);\n"
    "    vec2 f = fract(uv);\n"
    "    f = f * f * (3.0 - 2.0 * f);\n"
    "    float a = hash21(i);\n"
    "    float b = hash21(i + vec2(1.0, 0.0));\n"
    "    float c = hash21(i + vec2(0.0, 1.0));\n"
    "    float d = hash21(i + vec2(1.0, 1.0));\n"
    "    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float n = noise(uv * 16.0);\n"
    "    float edge = 0.05;\n"
    "    float alpha = smoothstep(n - edge, n + edge, u_progress);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha).bgra);\n"
    "}\n";

static const char *SHADER_SRC_CROSSZOOM =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2  u_center;\n"
    "uniform float u_wave_amp;\n"
    "const float PI = 3.14159265359;\n"
    "const int SAMPLES = 10;\n"
    "vec4 sample_radial_blur(highp sampler2D tex, vec2 uv, vec2 center, float zoom, float blur) {\n"
    "    vec4 accum = vec4(0.0);\n"
    "    float total_weight = 0.0;\n"
    "    vec2 dir = uv - center;\n"
    "    vec2 base_uv = center + dir * zoom;\n"
    "    for (int i = 0; i < SAMPLES; ++i) {\n"
    "        float norm_step = float(i) / float(SAMPLES - 1);\n"
    "        float offset = (norm_step - 0.5) * blur;\n"
    "        vec2 sample_uv = clamp(base_uv + dir * offset, 0.0, 1.0);\n"
    "        float weight = 1.0 - abs(norm_step - 0.5) * 1.4;\n"
    "        accum += texture(tex, sample_uv) * weight;\n"
    "        total_weight += weight;\n"
    "    }\n"
    "    return accum / total_weight;\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 center = (u_center.x > 0.0 || u_center.y > 0.0) ? u_center : vec2(0.5);\n"
    "    float strength = (u_wave_amp > 0.001) ? u_wave_amp : 0.4;\n"
    "    float peak = sin(u_progress * PI);\n"
    "    float blur = peak * strength * 0.6;\n"
    "    float zoom_a = 1.0 - u_progress * strength;\n"
    "    float zoom_b = 1.0 + (1.0 - u_progress) * strength;\n"
    "    vec4 color_a = sample_radial_blur(u_src_a, uv, center, zoom_a, blur);\n"
    "    vec4 color_b = sample_radial_blur(u_src_b, uv, center, zoom_b, blur);\n"
    "    vec4 result = mix(color_a, color_b, u_progress);\n"
    "    float flash = peak * 0.25;\n"
    "    result.rgb += vec3(flash);\n"
    "    imageStore(u_target, coord, clamp(result, 0.0, 1.0).bgra);\n"
    "}\n";

static const char *SHADER_SRC_SLIDE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_angle;\n"
    "uniform float u_wave_amp;\n"
    "const float PI = 3.14159265359;\n"
    "const int SAMPLES = 8;\n"
    "vec4 sample_directional_blur(highp sampler2D tex, vec2 base_uv, vec2 blur_vec) {\n"
    "    vec4 accum = vec4(0.0);\n"
    "    float total_w = 0.0;\n"
    "    for (int i = 0; i < SAMPLES; ++i) {\n"
    "        float step_norm = float(i) / float(SAMPLES - 1) - 0.5;\n"
    "        vec2 s_uv = base_uv + blur_vec * step_norm;\n"
    "        if (s_uv.x >= 0.0 && s_uv.x <= 1.0 && s_uv.y >= 0.0 && s_uv.y <= 1.0) {\n"
    "            float w = 1.0 - abs(step_norm) * 0.8;\n"
    "            accum += texture(tex, s_uv) * w;\n"
    "            total_w += w;\n"
    "        }\n"
    "    }\n"
    "    return (total_w > 0.0) ? (accum / total_w) : vec4(0.0);\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 dir = vec2(cos(u_angle), sin(u_angle));\n"
    "    float blur_strength = (u_wave_amp > 0.001) ? u_wave_amp : 0.08;\n"
    "    vec2 blur_vec = dir * sin(u_progress * PI) * blur_strength;\n"
    "    vec2 uv_a = uv + dir * u_progress;\n"
    "    vec2 uv_b = uv - dir * (1.0 - u_progress);\n"
    "    vec4 color_a = sample_directional_blur(u_src_a, uv_a, blur_vec);\n"
    "    vec4 color_b = sample_directional_blur(u_src_b, uv_b, blur_vec);\n"
    "    float proj = dot(uv - vec2(0.5), dir) / 1.41421356 + 0.5;\n"
    "    float edge = 0.02 + length(blur_vec) * 0.5;\n"
    "    float split = smoothstep(proj - edge, proj + edge, u_progress);\n"
    "    vec4 final_color = mix(color_a, color_b, split);\n"
    "    if (color_a.a == 0.0) final_color = color_b;\n"
    "    if (color_b.a == 0.0) final_color = color_a;\n"
    "    imageStore(u_target, coord, final_color.bgra);\n"
    "}\n";

static const char *SHADER_SRC_GLITCH =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_wave_freq;\n"
    "uniform float u_wave_amp;\n"
    "const float PI = 3.14159265359;\n"
    "float hash12(vec2 p) {\n"
    "    vec3 p3 = fract(vec3(p.xyx) * 0.1031);\n"
    "    p3 += dot(p3, p3.yzx + 33.33);\n"
    "    return fract((p3.x + p3.y) * p3.z);\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float bands = (u_wave_freq > 0.0) ? u_wave_freq : 35.0;\n"
    "    float intensity = (u_wave_amp > 0.0) ? u_wave_amp : 0.06;\n"
    "    float peak = sin(u_progress * PI);\n"
    "    float step_t = floor(u_progress * 24.0);\n"
    "    float slice_idx = floor(uv.y * bands);\n"
    "    float h = hash12(vec2(slice_idx, step_t));\n"
    "    float jitter = 0.0;\n"
    "    if (h > 0.60) {\n"
    "        jitter = (h - 0.80) * 2.5 * intensity * peak;\n"
    "    }\n"
    "    float split = peak * intensity * 0.6;\n"
    "    vec2 uv_r = clamp(uv + vec2(jitter + split, 0.0), 0.0, 1.0);\n"
    "    vec2 uv_g = clamp(uv + vec2(jitter, 0.0), 0.0, 1.0);\n"
    "    vec2 uv_b = clamp(uv + vec2(jitter - split, 0.0), 0.0, 1.0);\n"
    "    vec4 col_a;\n"
    "    col_a.r = texture(u_src_a, uv_r).r;\n"
    "    col_a.g = texture(u_src_a, uv_g).g;\n"
    "    col_a.b = texture(u_src_a, uv_b).b;\n"
    "    col_a.a = 1.0;\n"
    "    vec4 col_b;\n"
    "    col_b.r = texture(u_src_b, uv_r).r;\n"
    "    col_b.g = texture(u_src_b, uv_g).g;\n"
    "    col_b.b = texture(u_src_b, uv_b).b;\n"
    "    col_b.a = 1.0;\n"
    "    float block_h = hash12(floor(uv * vec2(24.0, 14.0)) + step_t);\n"
    "    float glitch_progress = u_progress + (block_h - 0.5) * peak * 0.35;\n"
    "    float mix_val = smoothstep(0.46, 0.54, glitch_progress);\n"
    "    vec4 result = mix(col_a, col_b, mix_val);\n"
    "    imageStore(u_target, coord, result.bgra);\n"
    "}\n";

static const char *SHADER_SRC_BURN =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_wave_freq;\n"
    "uniform float u_wave_amp;\n"
    "float hash21(vec2 p) {\n"
    "    p = fract(p * vec2(123.34, 456.21));\n"
    "    p += dot(p, p + 45.32);\n"
    "    return fract(p.x * p.y);\n"
    "}\n"
    "float value_noise(vec2 p) {\n"
    "    vec2 i = floor(p);\n"
    "    vec2 f = fract(p);\n"
    "    f = f * f * (3.0 - 2.0 * f);\n"
    "    float a = hash21(i);\n"
    "    float b = hash21(i + vec2(1.0, 0.0));\n"
    "    float c = hash21(i + vec2(0.0, 1.0));\n"
    "    float d = hash21(i + vec2(1.0, 1.0));\n"
    "    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);\n"
    "}\n"
    "float fbm(vec2 p) {\n"
    "    return 0.65 * value_noise(p) + 0.35 * value_noise(p * 2.1 + vec2(1.7, 3.2));\n"
    "}\n"
    "vec3 fire_color(float t) {\n"
    "    vec3 ash = vec3(0.08, 0.03, 0.02);\n"
    "    vec3 red = vec3(0.85, 0.10, 0.02);\n"
    "    vec3 orange = vec3(1.00, 0.55, 0.08);\n"
    "    vec3 yellow_white = vec3(1.00, 0.95, 0.70);\n"
    "    if (t < 0.25) return mix(ash, red, t / 0.25);\n"
    "    else if (t < 0.65) return mix(red, orange, (t - 0.25) / 0.40);\n"
    "    else return mix(orange, yellow_white, (t - 0.65) / 0.35);\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float scale = (u_wave_freq > 0.0) ? u_wave_freq : 14.0;\n"
    "    float flame_width = (u_wave_amp > 0.0) ? u_wave_amp : 0.08;\n"
    "    float n = fbm(uv * scale);\n"
    "    float d = n - u_progress;\n"
    "    vec4 color_a = texture(u_src_a, uv);\n"
    "    vec4 color_b = texture(u_src_b, uv);\n"
    "    if (d > flame_width) {\n"
    "        imageStore(u_target, coord, color_a.bgra);\n"
    "    } else if (d < -flame_width) {\n"
    "        imageStore(u_target, coord, color_b.bgra);\n"
    "    } else {\n"
    "        float burn_factor = smoothstep(flame_width, -flame_width, d);\n"
    "        vec4 base = mix(color_a, color_b, burn_factor);\n"
    "        float dist_norm = 1.0 - abs(d) / flame_width;\n"
    "        float heat = pow(dist_norm, 1.5);\n"
    "        vec3 flame = fire_color(heat) * (heat * 1.8);\n"
    "        vec3 charred = base.rgb * (1.0 - heat * 0.5);\n"
    "        vec3 result = charred + flame;\n"
    "        imageStore(u_target, coord, vec4(clamp(result, 0.0, 1.0), 1.0).bgra);\n"
    "    }\n"
    "}\n";

static const char *SHADER_SRC_RIPPLE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2  u_center;\n"
    "uniform float u_wave_freq;\n"
    "uniform float u_wave_amp;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 center = (u_center.x > 0.0 || u_center.y > 0.0) ? u_center : vec2(0.5);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    vec2 delta = uv - center;\n"
    "    delta.x *= aspect;\n"
    "    float dist = length(delta);\n"
    "    float max_dist = length(vec2(max(center.x, 1.0 - center.x) * aspect,\n"
    "                                 max(center.y, 1.0 - center.y))) + 0.1;\n"
    "    float current_radius = u_progress * max_dist;\n"
    "    float wave_width = 0.18;\n"
    "    float freq = (u_wave_freq > 0.0) ? u_wave_freq : 32.0;\n"
    "    float amp = (u_wave_amp > 0.0) ? u_wave_amp : 0.04;\n"
    "    float diff = dist - current_radius;\n"
    "    float decay = (1.0 - u_progress) * (1.0 - u_progress);\n"
    "    vec2 norm_dir = (dist > 0.0001) ? (delta / dist) : vec2(0.0);\n"
    "    norm_dir.x /= aspect;\n"
    "    float wave = 0.0;\n"
    "    float crest = 0.0;\n"
    "    if (abs(diff) < wave_width) {\n"
    "        float window = smoothstep(wave_width, 0.0, abs(diff));\n"
    "        wave = sin(diff * freq) * amp * decay * window;\n"
    "        crest = max(0.0, -wave / amp) * decay * 0.22;\n"
    "    }\n"
    "    vec2 refracted_uv = clamp(uv + norm_dir * wave, 0.0, 1.0);\n"
    "    vec4 color_a = texture(u_src_a, refracted_uv);\n"
    "    vec4 color_b = texture(u_src_b, refracted_uv);\n"
    "    float split = smoothstep(current_radius - 0.02, current_radius + 0.02, dist);\n"
    "    vec4 result = mix(color_b, color_a, split);\n"
    "    result.rgb += vec3(crest);\n"
    "    imageStore(u_target, coord, clamp(result, 0.0, 1.0).bgra);\n"
    "}\n";

static const char *SHADER_SRC_PIXELATE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    float d = sin(u_progress * 3.1415926535) * 64.0 + 1.0;\n"
    "    vec2 quant = (floor(vec2(coord) / d) * d + vec2(d * 0.5) + vec2(0.5)) / vec2(u_resolution);\n"
    "    vec4 c1 = texture(u_src_a, quant);\n"
    "    vec4 c2 = texture(u_src_b, quant);\n"
    "    vec4 col = mix(c1, c2, u_progress);\n"
    "    imageStore(u_target, coord, col.bgra);\n"
    "}\n";

static const char *SHADER_SRC_DOOM =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "float hash11(float p) {\n"
    "    p = fract(p * 0.1031);\n"
    "    p *= p + 33.33;\n"
    "    p *= p + p;\n"
    "    return fract(p);\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float col_idx = floor(float(coord.x) / 4.0);\n"
    "    float delay = hash11(col_idx) * 0.35;\n"
    "    float shift = clamp((u_progress * 1.35 - delay), 0.0, 1.0);\n"
    "    float pixel_shift = shift * float(u_resolution.y);\n"
    "    vec4 col;\n"
    "    if (float(coord.y) < pixel_shift) {\n"
    "        col = texture(u_src_b, uv);\n"
    "    } else {\n"
    "        vec2 melt_uv = uv;\n"
    "        melt_uv.y -= shift;\n"
    "        col = texture(u_src_a, melt_uv);\n"
    "    }\n"
    "    imageStore(u_target, coord, col.bgra);\n"
    "}\n";

static const char *SHADER_SRC_SWIRL =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2 u_center;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 center = (u_center.x > 0.0 || u_center.y > 0.0) ? u_center : vec2(0.5);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    vec2 d = uv - center;\n"
    "    d.x *= aspect;\n"
    "    float r = length(d);\n"
    "    float max_r = 0.85;\n"
    "    float angle_amt = sin(u_progress * 3.1415926535) * 8.0;\n"
    "    vec2 uv_dist = uv;\n"
    "    if (r < max_r) {\n"
    "        float factor = (1.0 - r / max_r);\n"
    "        float theta = factor * factor * angle_amt;\n"
    "        float cos_t = cos(theta);\n"
    "        float sin_t = sin(theta);\n"
    "        vec2 rotated = vec2(d.x * cos_t - d.y * sin_t, d.x * sin_t + d.y * cos_t);\n"
    "        rotated.x /= aspect;\n"
    "        uv_dist = center + rotated;\n"
    "    }\n"
    "    vec4 c1 = texture(u_src_a, uv_dist);\n"
    "    vec4 c2 = texture(u_src_b, uv_dist);\n"
    "    imageStore(u_target, coord, mix(c1, c2, u_progress).bgra);\n"
    "}\n";

static const char *SHADER_SRC_CUBE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 p_ndc = (uv - 0.5) * 2.0;\n"
    "    float theta = u_progress * 1.57079632679;\n"
    "    float zoom = 1.0 + 0.35 * sin(u_progress * 3.1415926535);\n"
    "    float d_cam = 2.5;\n"
    "    vec3 ro = vec3(0.0, 0.0, -d_cam);\n"
    "    vec3 rd = normalize(vec3(p_ndc.x * zoom, p_ndc.y * zoom, d_cam));\n"
    "    float cos_t = cos(theta);\n"
    "    float sin_t = sin(theta);\n"
    "    vec3 ro_rel = ro - vec3(0.0, 0.0, 1.0);\n"
    "    vec3 ro_cube = vec3(ro_rel.x * cos_t - ro_rel.z * sin_t, ro_rel.y, ro_rel.x * sin_t + ro_rel.z * cos_t);\n"
    "    vec3 rd_cube = vec3(rd.x * cos_t - rd.z * sin_t, rd.y, rd.x * sin_t + rd.z * cos_t);\n"
    "    float t_front = -1.0;\n"
    "    if (abs(rd_cube.z) > 1e-5) {\n"
    "        float t = (-1.0 - ro_cube.z) / rd_cube.z;\n"
    "        if (t > 0.0) {\n"
    "            vec3 hit = ro_cube + t * rd_cube;\n"
    "            if (abs(hit.x) <= 1.0 && abs(hit.y) <= 1.0) t_front = t;\n"
    "        }\n"
    "    }\n"
    "    float t_right = -1.0;\n"
    "    if (abs(rd_cube.x) > 1e-5) {\n"
    "        float t = (1.0 - ro_cube.x) / rd_cube.x;\n"
    "        if (t > 0.0) {\n"
    "            vec3 hit = ro_cube + t * rd_cube;\n"
    "            if (abs(hit.z) <= 1.0 && abs(hit.y) <= 1.0) t_right = t;\n"
    "        }\n"
    "    }\n"
    "    vec4 col = vec4(0.03, 0.03, 0.05, 1.0);\n"
    "    if (t_front > 0.0 && (t_right < 0.0 || t_front < t_right)) {\n"
    "        vec3 hit = ro_cube + t_front * rd_cube;\n"
    "        vec2 face_uv = vec2(hit.x * 0.5 + 0.5, hit.y * 0.5 + 0.5);\n"
    "        float shade = 0.65 + 0.35 * cos_t;\n"
    "        col = texture(u_src_a, face_uv) * vec4(vec3(shade), 1.0);\n"
    "    } else if (t_right > 0.0) {\n"
    "        vec3 hit = ro_cube + t_right * rd_cube;\n"
    "        vec2 face_uv = vec2((hit.z + 1.0) * 0.5, hit.y * 0.5 + 0.5);\n"
    "        float shade = 0.65 + 0.35 * sin_t;\n"
    "        col = texture(u_src_b, face_uv) * vec4(vec3(shade), 1.0);\n"
    "    }\n"
    "    imageStore(u_target, coord, col.bgra);\n"
    "}\n";

static const char *SHADER_SRC_LUMA =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "vec2 hash2(vec2 p) {\n"
    "    p = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));\n"
    "    return -1.0 + 2.0 * fract(sin(p) * 43758.5453123);\n"
    "}\n"
    "float noise2(vec2 p) {\n"
    "    vec2 i = floor(p);\n"
    "    vec2 f = fract(p);\n"
    "    vec2 u = f * f * (3.0 - 2.0 * f);\n"
    "    return mix(mix(dot(hash2(i + vec2(0.0, 0.0)), f - vec2(0.0, 0.0)),\n"
    "                   dot(hash2(i + vec2(1.0, 0.0)), f - vec2(1.0, 0.0)), u.x),\n"
    "               mix(dot(hash2(i + vec2(0.0, 1.0)), f - vec2(0.0, 1.0)),\n"
    "                   dot(hash2(i + vec2(1.0, 1.0)), f - vec2(1.0, 1.0)), u.x), u.y);\n"
    "}\n"
    "float fbm(vec2 p) {\n"
    "    float v = 0.0;\n"
    "    float a = 0.5;\n"
    "    mat2 rot = mat2(0.8, 0.6, -0.6, 0.8);\n"
    "    for (int i = 0; i < 4; i++) {\n"
    "        v += a * noise2(p);\n"
    "        p = rot * p * 2.0 + vec2(100.0);\n"
    "        a *= 0.5;\n"
    "    }\n"
    "    return v * 0.5 + 0.5;\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    float n = fbm(vec2(uv.x * aspect, uv.y) * 4.0);\n"
    "    float threshold = u_progress * 1.2 - 0.1;\n"
    "    float softness = 0.08;\n"
    "    float alpha = smoothstep(threshold - softness, threshold + softness, n);\n"
    "    vec4 c_old = texture(u_src_a, uv);\n"
    "    vec4 c_new = texture(u_src_b, uv);\n"
    "    float mix_val = 1.0 - alpha;\n"
    "    vec4 col = mix(c_old, c_new, mix_val);\n"
    "    float edge = 1.0 - abs(n - threshold) / (softness * 2.0);\n"
    "    if (edge > 0.0 && u_progress > 0.05 && u_progress < 0.95) {\n"
    "        float glow = edge * edge * sin(u_progress * 3.1415926535) * 0.25;\n"
    "        col.rgb += vec3(glow * 0.3, glow * 0.6, glow * 1.0);\n"
    "    }\n"
    "    imageStore(u_target, coord, col.bgra);\n"
    "}\n";

static const char *SHADER_SRC_LIGHT_LEAK =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec4 c1 = texture(u_src_a, uv);\n"
    "    vec4 c2 = texture(u_src_b, uv);\n"
    "    float mix_factor = smoothstep(0.25, 0.75, u_progress);\n"
    "    vec4 col = mix(c1, c2, mix_factor);\n"
    "    float sweep = u_progress * 1.6 - 0.3;\n"
    "    float dist = abs(uv.x + uv.y * 0.25 - sweep);\n"
    "    float flare_beam = exp(-dist * dist * 32.0);\n"
    "    vec2 orb1_center = vec2(sweep + 0.1, 0.4);\n"
    "    float orb1 = exp(-length(uv - orb1_center) * 6.0);\n"
    "    vec2 orb2_center = vec2(sweep - 0.2, 0.7);\n"
    "    float orb2 = exp(-length(uv - orb2_center) * 8.0);\n"
    "    float envelope = sin(u_progress * 3.1415926535);\n"
    "    envelope = envelope * envelope;\n"
    "    vec3 warm_flare = vec3(1.1, 0.65, 0.25) * flare_beam * 1.8;\n"
    "    warm_flare += vec3(1.0, 0.85, 0.4) * orb1 * 1.2;\n"
    "    warm_flare += vec3(0.9, 0.3, 0.5) * orb2 * 1.0;\n"
    "    col.rgb = clamp(col.rgb + warm_flare * envelope, 0.0, 1.0);\n"
    "    imageStore(u_target, coord, col.bgra);\n"
    "}\n";

static const char *SHADER_SRC_PAGE_CURL =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float R = 0.12;\n"
    "    float line = 1.02 - u_progress * 1.25;\n"
    "    float s = (uv.x + uv.y) * 0.5;\n"
    "    vec4 col;\n"
    "    if (s < line) {\n"
    "        col = texture(u_src_a, uv);\n"
    "    } else if (s < line + R) {\n"
    "        float dist = s - line;\n"
    "        vec2 uv_curl = uv - 2.0 * dist * vec2(0.5, 0.5);\n"
    "        if (uv_curl.x >= 0.0 && uv_curl.x <= 1.0 && uv_curl.y >= 0.0 && uv_curl.y <= 1.0) {\n"
    "            float curl_light = 0.85 + 0.35 * sin((dist / R) * 3.1415926535);\n"
    "            vec4 old_col = texture(u_src_a, uv_curl);\n"
    "            col = old_col * vec4(vec3(curl_light * 0.9), 1.0);\n"
    "        } else {\n"
    "            float shadow = 0.5 + 0.5 * smoothstep(0.0, R, dist);\n"
    "            col = texture(u_src_b, uv) * vec4(vec3(shadow), 1.0);\n"
    "        }\n"
    "    } else {\n"
    "        float drop_shadow_width = 0.08;\n"
    "        if (s < line + R + drop_shadow_width) {\n"
    "            float shadow = 0.65 + 0.35 * smoothstep(0.0, drop_shadow_width, s - (line + R));\n"
    "            col = texture(u_src_b, uv) * vec4(vec3(shadow), 1.0);\n"
    "        } else {\n"
    "            col = texture(u_src_b, uv);\n"
    "        }\n"
    "    }\n"
    "    imageStore(u_target, coord, col.bgra);\n"
    "}\n";

#endif /* WAYWAL_SHADERS_EMBEDDED_H */
