#ifndef WAYWAL_SHADERS_EMBEDDED_H
#define WAYWAL_SHADERS_EMBEDDED_H

static const char *SHADER_SRC_FADE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, u_progress));\n"
    "}\n";

static const char *SHADER_SRC_WIPE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_angle;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 dir = vec2(cos(u_angle), sin(u_angle));\n"
    "    float proj = dot(uv - vec2(0.5), dir) / 1.41421356 + 0.5;\n"
    "    float edge = 0.04;\n"
    "    float alpha = smoothstep(proj - edge, proj + edge, u_progress);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha));\n"
    "}\n";

static const char *SHADER_SRC_GROW =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2 u_center;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    vec2 delta = uv - u_center;\n"
    "    delta.x *= aspect;\n"
    "    float dist = length(delta);\n"
    "    float max_dist = length(vec2(max(u_center.x, 1.0 - u_center.x) * aspect,\n"
    "                                 max(u_center.y, 1.0 - u_center.y)));\n"
    "    float r = u_progress * (max_dist + 0.05);\n"
    "    float edge = 0.03 * (max_dist + 0.05);\n"
    "    float alpha = smoothstep(dist - edge, dist + edge, r);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha));\n"
    "}\n";

static const char *SHADER_SRC_OUTER =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform vec2 u_center;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float aspect = float(u_resolution.x) / float(u_resolution.y);\n"
    "    vec2 delta = uv - u_center;\n"
    "    delta.x *= aspect;\n"
    "    float dist = length(delta);\n"
    "    float max_dist = length(vec2(max(u_center.x, 1.0 - u_center.x) * aspect,\n"
    "                                 max(u_center.y, 1.0 - u_center.y)));\n"
    "    float r = (1.0 - u_progress) * (max_dist + 0.05);\n"
    "    float edge = 0.03 * (max_dist + 0.05);\n"
    "    float alpha = smoothstep(r - edge, r + edge, dist);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha));\n"
    "}\n";

static const char *SHADER_SRC_WAVE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "uniform float u_angle;\n"
    "uniform float u_wave_freq;\n"
    "uniform float u_wave_amp;\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    vec2 dir = vec2(cos(u_angle), sin(u_angle));\n"
    "    vec2 perp = vec2(-dir.y, dir.x);\n"
    "    float proj = dot(uv - vec2(0.5), dir) / 1.41421356 + 0.5;\n"
    "    float cross_proj = dot(uv - vec2(0.5), perp);\n"
    "    float wave = sin(cross_proj * u_wave_freq) * u_wave_amp;\n"
    "    float d = proj + wave;\n"
    "    float edge = 0.04;\n"
    "    float alpha = smoothstep(d - edge, d + edge, u_progress);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha));\n"
    "}\n";

static const char *SHADER_SRC_NOISE =
    "#version 310 es\n"
    "layout(local_size_x = 16, local_size_y = 16) in;\n"
    "layout(rgba8, binding = 0) writeonly uniform highp image2D u_target;\n"
    "layout(binding = 1) uniform highp sampler2D u_src_a;\n"
    "layout(binding = 2) uniform highp sampler2D u_src_b;\n"
    "uniform float u_progress;\n"
    "uniform ivec2 u_resolution;\n"
    "float hash21(vec2 p) {\n"
    "    p = fract(p * vec2(123.34, 456.21));\n"
    "    p += dot(p, p + 45.32);\n"
    "    return fract(p.x * p.y);\n"
    "}\n"
    "float noise(vec2 uv) {\n"
    "    vec2 i = floor(uv);\n"
    "    vec2 f = fract(uv);\n"
    "    f = f * f * (3.0 - 2.0 * f);\n"
    "    float a = hash21(i);\n"
    "    float b = hash21(i + vec2(1.0, 0.0));\n"
    "    float c = hash21(i + vec2(0.0, 1.0));\n"
    "    float d = hash21(i + vec2(1.0, 1.0));\n"
    "    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);\n"
    "}\n"
    "void main() {\n"
    "    ivec2 coord = ivec2(gl_GlobalInvocationID.xy);\n"
    "    if (coord.x >= u_resolution.x || coord.y >= u_resolution.y) return;\n"
    "    vec2 uv = (vec2(coord) + 0.5) / vec2(u_resolution);\n"
    "    float n = noise(uv * 16.0);\n"
    "    float edge = 0.05;\n"
    "    float alpha = smoothstep(n - edge, n + edge, u_progress);\n"
    "    vec4 a = texture(u_src_a, uv);\n"
    "    vec4 b = texture(u_src_b, uv);\n"
    "    imageStore(u_target, coord, mix(a, b, alpha));\n"
    "}\n";

#endif /* WAYWAL_SHADERS_EMBEDDED_H */
